/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.academico;

import java.util.Arrays;
import java.net.URISyntaxException;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.SpringApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.PropertySource;

@SpringBootApplication
@PropertySource("classpath:spring.properties")
public class Startup {
	
    public static void main(String[] args) throws URISyntaxException {
    
        System.setProperty("server.servlet.context-path", "/api");
		SpringApplication.run(Startup.class, args);
    }
}