/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.academico;

import java.util.Arrays;
import java.net.URISyntaxException;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.SpringApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.PropertySource;
import org.springframework.security.config.annotation.method.configuration.EnableGlobalMethodSecurity;

@SpringBootApplication
@PropertySource("classpath:spring.properties")
@EnableGlobalMethodSecurity(securedEnabled = true)
public class Startup {
	
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws URISyntaxException {
    
	    System.out.println(new Startup().getGreeting());
        System.setProperty("server.servlet.context-path", "/api");
		SpringApplication.run(Startup.class, args);
    }

    @Bean
	public CommandLineRunner commandLineRunner(ApplicationContext ctx) {
		return args -> {

			System.out.println("Let's inspect the beans provided by Spring Boot:");

			String[] beanNames = ctx.getBeanDefinitionNames();
			Arrays.sort(beanNames);
			for (String beanName : beanNames) {
				System.out.println(beanName);
			}
		};
	}
}
