/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.academico.domain.service;

import java.util.Optional;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mockito;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import com.academico.domain.repository.AlunoRepositoryInterface;
import com.academico.domain.entity.Aluno;
import com.academico.infrastructure.helper.DateHelper;
import static org.junit.Assert.*;

@RunWith(SpringRunner.class)
public class AlunoServiceTest {

    @MockBean
    private AlunoRepositoryInterface alunoRepository;

    @Test
    public void testBuscarCpfAluno() {

        //Given
        Aluno aluno = this.mockarAluno();
        Mockito.when(alunoRepository.findByCpf(aluno.getCpf())).thenReturn(Optional.of(aluno));

        //When
        Aluno found = alunoRepository.findByCpf(aluno.getCpf()).get();
        
        //Then
        assertEquals("O aluno não foi encontrado mas deveria", found.getCpf(), aluno.getCpf());
    }

    private Aluno mockarAluno() {
        Aluno aluno = new Aluno();
        aluno.setNome("Tiago Marques do Nascimento");
        aluno.setCpf("10747586703");
        aluno.setMatricula("1111");
        aluno.setDataNascimento(DateHelper.stringToDate("1989-11-03"));
        aluno.setDataMatricula(DateHelper.stringToDate("2020-01-01"));
        return aluno;
    }
}